config/routes.rb
Blog::Application.routes.draw do

  root to: 'posts#index', as: 'index'
  
  resources :authors
  resources :categories
  resources :posts do
    resources :comments
  end
  
  controller :posts do
    get  'posts_search' => :search
    post 'posts_search' => :find
  end
  
  controller :authors do
    get  'group_author_by_ip' => :group_author_by_ip
  end
  

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :posts
  has_many :comments
  
  validates_uniqueness_of :name
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
  belongs_to :author
  accepts_nested_attributes_for :author
  
  after_validation on: :create do
    if post.rating
      self.post.rating = (post.rating * post.comments.count + rating) / (post.comments.count + 1)
    else
      self.post.rating = rating
    end
    self.post.save
  end
  
  validates_length_of :rating, in: 1..5 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :delete_all
  belongs_to :category, touch: true
  belongs_to :author
  accepts_nested_attributes_for :author
  
  after_validation on: :create do
    self.rating ||= 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  def index
    @authors = Author.all
  end

  # GET /authors/1
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /authors/1
  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  # GET /group_author_by_ip
  def group_author_by_ip
    recurring_ips = Author.select(:ip).group(:ip).having('COUNT(ip) > 1').map(&:ip)
    @groups = {}
    recurring_ips.each { |ip| @groups[ip] = Author.where(ip: ip) }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def author_params
      params.require(:author).permit(:name, :ip)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /post/:post_id/comments
  def index
    @comments = Comment.all
  end

  # GET /post/:post_id/comments/1
  def show
  end

  # GET /post/:post_id/comments/new
  def new
    @comment = Comment.new
    @comment.post = Post.find_by(id: params[:post_id])
    @comment.build_author
  end

  # GET /post/:post_id/comments/1/edit
  def edit
  end

  # POST /post/:post_id/comments
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by(id: params[:post_id])
    @comment.post = @post
    if author = Author.find_by(name: comment_params[:author_attributes][:name])
      @comment.author = author
    end
    @comment.author_ip = request.env['REMOTE_ADDR']
    
    respond_to do |format|
      if @comment.save
        flash[:notice] = 'Comment was successfully created.'
        format.html { redirect_to [@post, @comment] }
        format.js { render action: 'create' }
      else
        flash[:notice] = 'Comment was not created.'
        format.html { render action: 'new' }
        format.js { render action: 'create' }
      end
    end
  end

  # PATCH/PUT /post/:post_id/comments/1
  def update
    if @comment.update(comment_params)
      redirect_to [@comment.post, @comment], notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /post/:post_id/comments/1
  def destroy
    @comment.destroy
    redirect_to posts_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:description, :rating, author_attributes: [:name])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.order(:rating).reverse_order.take 10
    fresh_when @posts
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.build_author
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if author = Author.find_by(name: post_params[:author_attributes][:name])
      @post.author = author
    end
    @post.author.ip = request.env['REMOTE_ADDR']
    
    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post has been successfully created.'
        format.html { redirect_to @post }
        format.js { render action: 'create' }
      else
        flash[:notice] = 'Post was not created.'
        format.html { render action: 'new' }
        format.js { render action: 'create' }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end
  
  # GET /posts_search
  def search
  end
  
  # POST /posts_find?rating_down=:rating_down&rating_up=:rating_up&date=:date
  def find
    @posts = Post.where("(rating BETWEEN ? AND ?) AND (created_at BETWEEN ? AND ?)",
                find_post_params[:rating_from],
                find_post_params[:rating_to],
                find_post_params[:date].to_date.beginning_of_day,
                find_post_params[:date].to_date.end_of_day)
    if @posts.empty?
      flash[:notice] = 'Nothing!'
    else
      flash[:notice] = nil
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :description, :category_id, author_attributes: [:name])
    end
    
    def find_post_params
      params.require(:find_post).permit(:rating_from, :rating_to, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/group_author_by_ip.html.erb
<h1>Authors grouped by ip</h1>

<% begin %>
  <% @groups.each_key do |group| %>
    <h3><%= group %>:</h3>
    <ul id="authors">
      <% @groups[group].each do |author| %>
        <li><%= link_to author.name, author %></li>
      <% end %>
    </ul>
  <% end %>
<% rescue %>
  <h3>No have groups!</h3>
<% end %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.ip %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @author.ip %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<% cache comment do %>
  <li>
    Author name: <%= comment.author.name %><br/>
    Rating: <%= comment.rating %><br/>
    Author IP: <%= comment.author.ip %><br/>
    Description: <p><%= comment.description %></p>
  </li>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@comment.post, @comment], remote: true do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.select :rating, options_for_select((1..5)) %>
  </div>
  <%= f.fields_for :author do |author_form| %>
    <div class="field">
      <%= author_form.label :name %>
      <%= author_form.text_field :name %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#new_comment").replaceWith("<%=j link_to 'New Comment', new_post_comment_path(@post), remote: true, id: :new_comment %>");
$("#notice").html("<%=j notice %>");
$("<%=j render @comment %>").appendTo("#comments");
$("#post_rating").html("<strong>Rating: </strong><%=j sprintf('%.2f', @post.rating) %>");

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.post, @comment] %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Author ip</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.author_ip %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', [comment.post, comment] %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
        <td><%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_post_comment_path(Post.first) %>

app/views/comments/new.html.erb
<div id='new_comment'>
  <h1>New comment</h1>

  <%= render 'form' %>

  <%= link_to 'Back', post_path(@comment.post) %>
</div>

app/views/comments/new.js.erb
$("#new_comment").replaceWith("<%=j render template: 'comments/new.html.erb' %>");

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>Author ip:</strong>
  <%= @comment.author_ip %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@comment.post, @comment) %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= controller.controller_name %>_page">
    <div id="banner">
      <% image_tag("logo.png") %>
      <span id='title'>
        <%= @page_title || 'Blog' %>
      </span>
    </div>
    <div id="columns">
      <div id="side">
        <ul>
          <li><%= link_to_unless_current 'Home', index_path %></li>
          <li><%= link_to_unless_current 'Search Post', posts_search_path %></li>
          <li><%= link_to_unless_current "Group author by IP", group_author_by_ip_path %></li>
        </ul>
      </div>
      <div id="main">
    
        <%= yield %>
    
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%= f.fields_for :author do |author_form| %>
    <div class="field">
      <%= author_form.label :name %>
      <%= author_form.text_field :name %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% cache post do %>
  <li>
    Title: <%= post.title %><br/>
    Comments count: <%= post.comments.count rescue 0 %><br/>
    Description: <p><%= post.description %></p>
    Category: <%= post.category.name %><br/>
    Rating: <%= sprintf('%.2f', post.rating) %><br/>
    Author name: <%= post.author.name %><br/>
    Author ip: <%= post.author.ip %><br/>
    Created at: <%= post.created_at.to_date %><br/>
    <%= link_to 'Show', post %>
  </li>
<% end %>

app/views/posts/create.js.erb
$("#new_post").replaceWith("<%=j link_to 'New Post', new_post_path, remote: true, id: :new_post %>");
$("#notice").html("<%=j notice %>");

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/find.js.erb
$("#posts").html("<%=j render @posts %>");
$("#notice").html("<%=j notice %>");

app/views/posts/index.html.erb
<% cache @posts do %>
  <h1>Top 10 posts</h1>

  <p id="notice"><%= notice %></p>
  <%= link_to 'New Post', new_post_path, remote: true, id: :new_post %>
  <br/>
  <ul id='posts'>
    <%= render @posts %>
  </ul>
<% end %>

app/views/posts/new.html.erb
<div id='new_post'>
  <h1>New post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/new.js.erb
$("#new_post").replaceWith("<%=j render template: 'posts/new.html.erb' %>");

app/views/posts/search.html.erb
<div id="search_form">
  <%= form_for :find_post, remote: true do |f| %>
    <fieldset>
      <legend>Search</legend>
      <div>
        Rating from: <%= f.select :rating_from, options_for_select((1..5).step(0.5)) %>
                 to: <%= f.select :rating_to,   options_for_select((1..5).step(0.5)) %>
      </div>
      <div>
        Date: <%= f.date_field :date, placeholder: '23.12.2013' %>
      </div>
      <div>
        <%= submit_tag "Find" %> 
      </div>
    </fieldset> 
  <% end %>
</div>
<div id='posts'>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Comments count:</strong>
  <%= @post.comments.count rescue 0 %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p id='post_rating'>
  <strong>Rating: </strong>
  <%= sprintf('%.2f', @post.rating) %>
</p>

<p>
  <strong>Author name:</strong>
  <%= @post.author.name %>
</p>

<p>
  <strong>Author IP:</strong>
  <%= @post.author.ip %>
</p>

<strong>Comments:</strong>
<% cache @post.comments do %>
  <ul id='comments'>
    <%= render @post.comments %>
  </ul>
<% end %>
<%= link_to 'New comment', new_post_comment_path(@post), remote: true, id: :new_comment %>
<br/>
<br/>

<%= link_to 'Back to posts', posts_path %>